### ISSUE TITLE
ETH3D dataset

### ISSUE THREAD

**Issue by LeoPerelli** [jytime/Deep-SfM-Revisited#22]
Hey @jytime, thank you very much for your support, really appreciate your time!

As your work seems to outperform DeepSfM on all datasets tested, I wanted to replicate this result on ETH3D dataset.
I tried to run the network as is, but the results are not great. I suspect that surely the KITTI checkpoint requires some finetuning to the feature extractor, which I will perform on the DeMoN datasets. 

1) Is there any chance you can share the checkpoints on the DeMoN datasets? 

2) Do you believe that there is anything else which should be changed to test the method on ETH3D? 

Thanks!
Best

**Comment by jytime** [comment]
Hi @LeoPerelli ,

Unfortunately you may need to retrain the model, because the optical flow estimator we used may not suit the ETH3D dataset. Our model was not designed to consider ETH3D, so please feel free to skip if you need to report our results on ETH3D in a paper. If you want to have a try, I would recommend first trying 2D matches from https://github.com/cvg/Hierarchical-Localization, and retrain the model on DeMoNs with the new matches.

Best,
Jianyuan

**Comment by LeoPerelli** [comment]
Thanks a lot for pointing out the resource!

Do you believe that only the optical flow requires some fine tuning or also the depth net, feature extractors etc?
I tried running the algorithm with ground truth poses but it still underperforms the other methods, while I was expecting it could beat them.
Of course I want to put the model in the best possible conditions to perform adequately!

**Comment by jytime** [comment]
Hi @LeoPerelli ,

When the optical flow estimator is changed, the depth net and feature extractor should be further tuned to fit the new pattern of poses. At the same time, it is true that KITTI is far away from ETH3D, so that trained on a dataset closer to ETH3D would be beneficial. 

If you want to retrain/finetune the model on another dataset, it is safe to keep cfg.NORM_TARGET still as 0.6. I used this to ensure the distribution of "depth_bw" to fit a range (sorry I cannot remember the distribution exactly). You can also remove it if you find the model can still be trained well.

Best,
Jianyuan

**Comment by LeoPerelli** [comment]
Hey @jytime, thanks so much for your answer!

Now I understand what the NORM_TARGET was used for.

1) I guess that the DeMoN checkpoint is likely lost, but in case you believe there is any chance you can retrieve it it would be super helpful!

2) What exactly do you mean with "pattern of poses" in: 
> the depth net and feature extractor should be further tuned to fit the new pattern of poses

Does the KITTI dataset pose pattern bias the network somehow?

Thanks for your help,
Leo

**Comment by jytime** [comment]
Hi @LeoPerelli ,

Yes. As the KITTI dataset is derived from video sequences captured by a moving car, the car typically follows a consistent direction, and consecutive frames within the dataset are close to each other. I am not familiar with ETH3D but it looks not like this.

Best,
Jianyuan

**Comment by LeoPerelli** [comment]
Thanks @jytime,

I was suspecting this could bias the network but did not think to this extent.

Let me know if by any chance you are able to find the Demon checkpoint!

Should have ended my questions :)

Again, really appreciate your support.

Best, 
Leo
